In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [19]:
df = pd.read_csv("datasets/student_binary_classification.csv")
print(df.info())
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudyHours  12 non-null     float64
 1   Result      12 non-null     str
dtypes: float64(1), str(1)
memory usage: 324.0 bytes
None
       StudyHours
count   12.000000
mean     4.333333
std      2.081666
min      1.000000
25%      2.875000
50%      4.250000
75%      5.625000
max      8.000000

In [20]:
df

    StudyHours Result
0          1.0   Fail
1          2.0   Fail
2          2.5   Fail
3          3.0   Fail
4          3.5   Fail
5          4.0   Pass
6          4.5   Pass
7          5.0   Pass
8          5.5   Pass
9          6.0   Pass
10         7.0   Pass
11         8.0   Pass

In [21]:
df["Result"] = df["Result"].map({
    "Fail" : 0,
    "Pass" : 1
})
df

    StudyHours  Result
0          1.0       0
1          2.0       0
2          2.5       0
3          3.0       0
4          3.5       0
5          4.0       1
6          4.5       1
7          5.0       1
8          5.5       1
9          6.0       1
10         7.0       1
11         8.0       1

In [31]:
X = df[["StudyHours"]]
y = df["Result"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
model = LogisticRegression()
model.fit(X_train,y_train)
prediction = model.predict(X_test)
prediction

comparison = pd.DataFrame({
    "Actual" : y_test,
    "Prediction" : prediction
})
comparison

    Actual  Prediction
10       1           1
9        1           1
0        0           0

In [35]:
accuracy = accuracy_score(y_test,prediction)
print(accuracy * 100, "%")

100.0 %

In [38]:
new_student = pd.DataFrame({
    "StudyHours" : [4.5]
})
new_prediction = model.predict(new_student)
new_prediction

array([1])

In [39]:
import math
math.e

2.718281828459045

In [12]:
df = pd.read_csv("datasets/student_multiple_binary_classification.csv")

In [22]:
df = pd.read_csv("datasets/student_multiple_binary_classification.csv")
df["Result"] = df["Result"].map({
    "Pass" : 1,
    "Fail" : 0
})
X = df[["StudyHours", 
        "PreviousMarks",
        "Attendance"]]

y = df["Result"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

model = LogisticRegression()
model.fit(X_train,y_train)
prediction = model.predict(X_test)
print(prediction)
print(X_test)
print(y_test)

accuracy = accuracy_score(y_test,prediction)
print(accuracy)
new_student = pd.DataFrame({
    "StudyHours" : [6],
    "PreviousMarks" : [69],
    "Attendance" : [90]
})
predict = model.predict(new_student)
print(predict)
prediction = model.predict_proba(new_student)
print(prediction)

[0 1 0]
    StudyHours  PreviousMarks  Attendance
10           3             48          72
9            6             70          88
0            2             38          70
10    0
9     1
0     0
Name: Result, dtype: int64
1.0
[1]
[[4.80100592e-08 9.99999952e-01]]

In [ ]:
df = pd.read_csv("datasets/student_multiclass_single_feature.csv")