In [3]:
import pandas as pd

In [22]:
dd = pd.read_csv("datasets/daraz_dataset.csv")
#print(dd.info())
#print(dd["TotalAmount"].max())
#print(dd["TotalAmount"].min())
#print(dd["TotalAmount"].mean())
#print(dd.columns)
#print(dd[["CustomerName", "District"]])
#print(dd.head(1))
#print(dd.iloc[1]) 1 index ko row lai tanyo
#print(dd.iloc[11]) 11 index ko row lai tanyo
#print(dd.iloc[5:10]) 5 to 10-1 index ko row lai tanyo 
#print(dd.iloc[0,2]) special cell lai capture garna milxa
#print(dd.iloc[:,8])
#print(dd.iloc[-1])   
#print(dd.iloc[0:5, 0:3]) five column and three rows
#print(dd.loc[dd["District"]=="Kathmandu"]) 
#print(dd.loc[dd["TotalAmount"] > 3000]) amount greatter than 3000

#print(dd[(dd["District"]=="Kathmandu") & (dd["PaymentMethod"]=="eSewa")])
#print(dd[(dd["Category"] == "Electronics") & (dd["Rating"] == 5)])
# print(dd.iloc[5:8])


#print(dd.sort_values("TotalAmount",ascending=False)) Defauld ascending True hunxa

In [5]:

bdd = pd.read_csv("datasets/bad_daraz_dataset.csv")
print(bdd)

    product_id product_name     category  price discount_percent  rating  \
0            1       Laptop  Electronics  75000               10     4.8
1            2        Phone  Electronics    NaN               15     4.6
2            3        Shoes      Fashion   3500               5%     4.2
3            4      T-Shirt      Fashion   1500               20     NaN
4            5        Watch  Accessories   5500               10     4.5
5            6   Headphones  Electronics   4200              NaN     4.1
6            7       Laptop  Electronics  75000               10     4.8
7            8          Bag      Fashion    abc               12     3.9
8            9        Mouse  Electronics   1800                5     4.3
9           10     Keyboard  Electronics   2500                5     4.4
10          11       Bottle         Home    800                0     5.5
11          12        Chair    Furniture  -2500               10     4.0
12          12        Chair    Furniture  -2500               10     4.0
13          12        Chair    Furniture  -2500               10     4.0

           stock       seller         city      brand gender_target      age  \
0             25      TechHub    Kathmandu       Dell        Unisex       25
1             40  GadgetNepal      Pokhara    Samsung        Unisex       30
2             60   FashionHub      Itahari       Nike          Male       22
3            150        Style   Biratnagar     Adidas        Female   Female
4   Out of Stock        TimeX    Kathmandu      Casio          Male       28
5             75     AudioPro      Pokhara        JBL        Unisex      24
6             25      TechHub    Kathmandu       Dell        Unisex       25
7             45     CarryAll       Dharan  Wildcraft        Female       19
8            NaN      TechHub    Kathmandu   Logitech        Unisex      NaN
9             35     TechHub    Kathmandu    Logitech        Unisex       21
10           100    HomeStore     Janakpur    Generic        Unisex       26
11            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown
12            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown
13            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown

    reviews
0       120
1       210
2        55
3        30
4        80
5        65
6       120
7        18
8        90
9       110
10       12
11       44
12       44
13       44

In [12]:
bdd.isnull()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
bdd.isnull().sum()

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               1
seller              0
city                0
brand               0
gender_target       0
age                 1
reviews             0
dtype: int64

In [31]:
#bdd.fillna(0) fill 0 in missing value
bdd["price"] = pd.to_numeric(bdd["price"], errors="coerce")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [27]:
#bdd["price"] = bdd["price"].fillna(bdd["price"].mean())
#bdd
import pandas as pd
bdd = pd.read_csv("datasets/bad_daraz_dataset.csv")
bdd["price"] = pd.to_numeric(bdd["price"], errors = "coerce")
bdd["price"] = bdd["price"].fillna(bdd["price"].mean())
print(bdd)

    product_id product_name     category    price discount_percent  rating  \
0            1       Laptop  Electronics  75000.0               10     4.8
1            2        Phone  Electronics  13525.0               15     4.6
2            3        Shoes      Fashion   3500.0               5%     4.2
3            4      T-Shirt      Fashion   1500.0               20     NaN
4            5        Watch  Accessories   5500.0               10     4.5
5            6   Headphones  Electronics   4200.0              NaN     4.1
6            7       Laptop  Electronics  75000.0               10     4.8
7            8          Bag      Fashion  13525.0               12     3.9
8            9        Mouse  Electronics   1800.0                5     4.3
9           10     Keyboard  Electronics   2500.0                5     4.4
10          11       Bottle         Home    800.0                0     5.5
11          12        Chair    Furniture  -2500.0               10     4.0
12          12        Chair    Furniture  -2500.0               10     4.0
13          12        Chair    Furniture  -2500.0               10     4.0

           stock       seller         city      brand gender_target      age  \
0             25      TechHub    Kathmandu       Dell        Unisex       25
1             40  GadgetNepal      Pokhara    Samsung        Unisex       30
2             60   FashionHub      Itahari       Nike          Male       22
3            150        Style   Biratnagar     Adidas        Female   Female
4   Out of Stock        TimeX    Kathmandu      Casio          Male       28
5             75     AudioPro      Pokhara        JBL        Unisex      24
6             25      TechHub    Kathmandu       Dell        Unisex       25
7             45     CarryAll       Dharan  Wildcraft        Female       19
8            NaN      TechHub    Kathmandu   Logitech        Unisex      NaN
9             35     TechHub    Kathmandu    Logitech        Unisex       21
10           100    HomeStore     Janakpur    Generic        Unisex       26
11            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown
12            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown
13            -5      FurniCo     Lalitpur       IKEA        Unisex  Unknown

    reviews
0       120
1       210
2        55
3        30
4        80
5        65
6       120
7        18
8        90
9       110
10       12
11       44
12       44
13       44

In [54]:
#dummy = pd.Series(["100", "200", "manish"])
#pd.to_numeric(dummy,errors="coerce")

bdd["age"] = pd.to_numeric(bdd["age"], errors = "coerce")
bdd["age"] = bdd["age"].fillna(bdd["age"].median())
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,16730.0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,16730.0,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [45]:
bdd.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [59]:
bdd["discount_percent"] = bdd["discount_percent"].str.replace("%","")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discount_percet
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
1,2,Phone,Electronics,16730.0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210,15
2,3,Shoes,Fashion,3500.0,5,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55,5
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30,20
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80,10
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65,NaN
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
7,8,Bag,Fashion,16730.0,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18,12
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90,5
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110,5
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12,0
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10

In [32]:
print(bdd[bdd["city"] == "Kathmandu"])

   product_id product_name     category    price discount_percent  rating  \
0           1       Laptop  Electronics  75000.0               10     4.8
4           5        Watch  Accessories   5500.0               10     4.5
6           7       Laptop  Electronics  75000.0               10     4.8
8           9        Mouse  Electronics   1800.0                5     4.3

          stock   seller       city     brand gender_target  age  reviews
0            25  TechHub  Kathmandu      Dell        Unisex   25      120
4  Out of Stock    TimeX  Kathmandu     Casio          Male   28       80
6            25  TechHub  Kathmandu      Dell        Unisex   25      120
8           NaN  TechHub  Kathmandu  Logitech        Unisex  NaN       90

In [3]:
bdd.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        12 non-null     int64
 1   product_name      12 non-null     str
 2   category          12 non-null     str
 3   price             11 non-null     str
 4   discount_percent  11 non-null     str
 5   rating            11 non-null     float64
 6   stock             11 non-null     str
 7   seller            12 non-null     str
 8   city              12 non-null     str
 9   brand             12 non-null     str
 10  gender_target     12 non-null     str
 11  age               11 non-null     str
 12  reviews           12 non-null     int64
dtypes: float64(1), int64(2), str(10)
memory usage: 1.3 KB

In [4]:
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [6]:
bdd.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [14]:
import pandas as pd

# 1. Load your existing dataset
df = pd.read_csv('datasets/bad_daraz_dataset.csv')

# 2. Define the new row data exactly matching your columns
new_row_data = [12, 'Chair', 'Furniture', '-2500', '10', 4.0, '-5', 'FurniCo', 'Lalitpur', 'IKEA', 'Unisex', 'Unknown', 44]

# 3. Insert or overwrite directly at index 13
df.loc[13] = new_row_data

# 4. Save the entire updated DataFrame back to your CSV
df.to_csv('datasets/bad_daraz_dataset.csv', index=False)

# 5. Verify it worked by printing the row
df.loc[[13]]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [15]:
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [16]:
df.loc[13]

product_id                 12
product_name            Chair
category            Furniture
price                   -2500
discount_percent           10
rating                    4.0
stock                      -5
seller                FurniCo
city                 Lalitpur
brand                    IKEA
gender_target          Unisex
age                   Unknown
reviews                    44
Name: 13, dtype: object

In [20]:
bdd.duplicated("product_id")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [15]:
bdd.drop_duplicates()
bdd.drop_duplicates("product_id")
bdd.drop_duplicates(subset="product_id", inplace = True)
bdd
bdd.drop_duplicates(subset="product_id", keep = "last", inplace = True)
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [34]:
bdd["price"] = pd.to_numeric(bdd["price"], errors = "coerce")
bdd["price"] = bdd["price"].fillna(bdd["price"].mean())
bdd = bdd[bdd["price"]<0]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [28]:
bdd[bdd["rating"]>5]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12

In [6]:
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [10]:
bdd.duplicated("product_id")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
dtype: bool

In [16]:
bdd.city()

TypeError: 'Series' object is not callable

In [17]:
bdd.city

0       Kathmandu
1         Pokhara
2         Itahari
3      Biratnagar
4       Kathmandu
5         Pokhara
6       Kathmandu
7          Dharan
8       Kathmandu
9      Kathmandu
10       Janakpur
11       Lalitpur
Name: city, dtype: str

In [23]:
bdd["city"].str.lstrip()
bdd["city"].str.lower()
bdd["city"].str.title()

0       Kathmandu
1         Pokhara
2         Itahari
3      Biratnagar
4       Kathmandu
5         Pokhara
6       Kathmandu
7          Dharan
8       Kathmandu
9      Kathmandu
10       Janakpur
11       Lalitpur
Name: city, dtype: str

In [17]:
import pandas as pd
sd = pd.DataFrame({
    "Salary" : [1000,2000,3000,5000,7000,8000,9000,12000,50000]
})
sd

   Salary
0    1000
1    2000
2    3000
3    5000
4    7000
5    8000
6    9000
7   12000
8   50000

In [6]:
median = sd["Salary"].quantile(0.50)
median

np.float64(6000.0)

In [12]:
q1=sd["Salary"].quantile(0.25)
q3=sd["Salary"].quantile(0.75)

# IQR
iqr = q3-q1

lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

upper_bound

np.float64(16500.0)

In [18]:
outliers = sd[(sd["Salary"] < lower_bound)|(sd["Salary"] > upper_bound)]
print(outliers)

   Salary
8   50000

In [37]:
bdd["price"] =pd.to_numeric(bdd["price"],errors="coerce")

mean = bdd["price"].mean()
std = bdd["price"].std()

bdd["z_score"] = (bdd["price"]-mean) / std
outliers = bdd[bdd["z_score"].abs() > 2]
outliers

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.317666
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.317666

In [25]:
print(dd.columns.tolist())

['OrderID', 'OrderDate', 'CustomerName', 'Age', 'Gender', 'District', 'Category', 'Product', 'Quantity', 'UnitPrice', 'DiscountPercent', 'TotalAmount', 'PaymentMethod', 'Rating', 'OrderStatus']