In [2]:
import pandas as pd

In [3]:
dd = pd.read_csv("datasets/bad_daraz_dataset.csv")

In [39]:
dd["price"] = pd.to_numeric(dd["price"], errors = "coerce")

In [11]:
dd = dd.iloc[:-3]

# 3. Save the updated DataFrame back to the CSV file
dd.to_csv('datasets/bad_daraz_dataset.csv', index=False)

In [12]:
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12

In [45]:
q1 = dd["price"].quantile(0.25)
q3 = dd["price"].quantile(0.75)
median = dd["price"].median()

IQR = q3 - q1

lower_bound = q1 - (1.5 * IQR)
upper_bound = q3 + (1.5 * IQR)
median

np.float64(3500.0)

In [22]:
outliers = dd[(dd["price"] < lower_bound)|(dd["price"] > upper_bound)]
outliers

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120

In [24]:
len(outliers)

2

In [41]:
dd.loc[(dd["price"] < lower_bound)|(dd["price"] > upper_bound),"price"] = median
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,3500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,3500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12

In [ ]:
dd["price"].clip(lower_bound,upper_bound)

In [36]:
# for category, group in dd.groupby('category'):
#     # print(category)
#     # print("Rows" ,len(data))
#     # print(data)
# # electronics =   dd.groupby("category").get_group("Electronics")
# # electronics

# for city,data in dd.groupby("city"):
#     print(data)

# itahari = dd.groupby("city").get_group("Kathmandu")
# itahari
# dd.groupby("category")["product_name"].count()
# dd.groupby("category")["product_name"].max()
# dd.groupby("category")["price"].min()

dd.groupby("category")["price"].agg(["max","max","count"])

                 max      max  count
category
Accessories   5500.0   5500.0      1
Electronics  75000.0  75000.0      5
Fashion       3500.0   3500.0      2
Home           800.0    800.0      1

In [37]:
dd.groupby("category")["rating"].min()

category
Accessories    4.5
Electronics    4.1
Fashion        3.9
Home           5.5
Name: rating, dtype: float64

In [44]:
dd.groupby("category").agg({
    "price" : "mean",
    "rating" : "max",
    "reviews" : "sum",
})

               price  rating  reviews
category
Accessories   5500.0     4.5       80
Electronics  31700.0     4.8      715
Fashion       2500.0     4.2      103
Home           800.0     5.5       12