In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("datasets/LMS_Dirty_Dataset.csv")
#1. Dataset Exploration
df.head(10)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed

In [4]:
df.tail(10)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
340,341,Hari,Digital Marketing,Biratnagar,31,Female,2026-06-10,5000,20,Pending,96.0,38,71,5,Ishan,9831430348,user340@gmail.com,Ongoing
341,342,Gita,Flutter,Biratnagar,32,Female,2026-04-16,5000,10,Paid,54.0,33,61,5,Ishan,9865928299,user341@gmail.com,Ongoing
342,343,Aarav,UI/UX,Itahari,18,Male,2026-03-01,7000,10,Paid,45.0,85,46,5,Manish,9832055006,user342@gmail.com,Completed
343,344,Gita,Python with AI/ML,Kathmandu,33,Male,2026-05-07,5000,20,Paid,67.0,57,30,4,Samriddha,9828498406,user343@gmail.com,Ongoing
344,345,Gita,Digital Marketing,Pokhara,29,Male,2026-05-18,10000,10,Paid,71.0,45,89,4,Manish,9847970014,user344@gmail.com,Completed
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [6]:
df.shape

(350, 18)

In [8]:
df.columns

Index(['student_id', 'student_name', 'course', 'city', 'age', 'gender',
       'enrollment_date', 'course_fee', 'discount', 'payment_status',
       'attendance_percent', 'assignment_score', 'final_score', 'rating',
       'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [12]:
df.dtypes

student_id              int64
student_name              str
course                    str
city                      str
age                     int64
gender                    str
enrollment_date           str
course_fee              int64
discount                int64
payment_status            str
attendance_percent    float64
assignment_score        int64
final_score             int64
rating                  int64
mentor                    str
phone                     str
email                     str
completion_status         str
dtype: object

In [13]:
df.describe()

,student_id,age,course_fee,discount,attendance_percent,assignment_score,final_score,rating
count,350.000000,350.000000,350.000000,350.000000,349.000000,350.000000,350.000000,350.000000
mean,175.500000,26.174286,10085.711429,9.600000,70.154728,67.011429,65.011429,3.960000
std,101.180532,5.485686,53109.214627,7.929489,16.697929,20.686773,20.556718,0.817852
min,1.000000,17.000000,-5000.000000,0.000000,40.000000,-5.000000,30.000000,3.000000
25%,88.250000,21.000000,5000.000000,0.000000,58.000000,51.000000,47.000000,3.000000
50%,175.500000,27.000000,7000.000000,10.000000,70.000000,69.000000,65.000000,4.000000
75%,262.750000,31.000000,10000.000000,20.000000,83.000000,85.750000,82.000000,5.000000
max,350.000000,35.000000,999999.000000,20.000000,100.000000,100.000000,100.000000,5.000000

In [14]:
#2.Data Cleaning
#remove duplicates
df = df.drop_duplicates()

In [15]:
#handle missing value
df['attendance_percent'] = df['attendance_percent'].fillna(df['attendance_percent'].median())
#Convert incorrect datatype into approptiate format
df['enrollment_date'] = pd.to_datetime(df['enrollment_date'])

In [17]:
#Standardize inconsistant value
df['city'] = df['city'].replace({'ktm': 'Kathmandu'})
df['course'] = df['course'].replace({'Pythn AI': 'Python with AI/ML'})

In [18]:
#Fix negative values
df['course_fee'] = df['course_fee'].abs()
df['assignment_score'] = df['assignment_score'].abs()

In [5]:
# 3. Outlier detection using IQR
cols = ['course_fee', 'attendance_percent', 'assignment_score', 'final_score']
q1 = df[cols].quantile(0.25)
q3 = df[cols].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
iqr_summary = pd.DataFrame({
    'Q1': q1,
    'Q3': q3,
    'IQR': iqr,
    'Lower Bound': lower_bound,
    'Upper Bound': upper_bound
})
print(iqr_summary)

                        Q1        Q3      IQR  Lower Bound  Upper Bound
course_fee          5000.0  10000.00  5000.00    -2500.000    17500.000
attendance_percent    58.0     83.00    25.00       20.500      120.500
assignment_score      51.0     85.75    34.75       -1.125      137.875
final_score           47.0     82.00    35.00       -5.500      134.500

In [45]:
#Outlier Handeling
outlier = ((df[cols] < lower_bound) | (df[cols] > upper_bound)).any(axis=1)
df_remove = df[~outlier]
print(df_remove)

     student_id student_name             course        city  age  gender  \
0             1         Gita         MERN Stack   Kathmandu   17  Female
1             2        Nabin       Data Science     Itahari   29  Female
2             3         Gita         MERN Stack      Dharan   20  Female
3             4         Gita  Digital Marketing     Itahari   20  Female
4             5         Gita       Data Science     Itahari   19    Male
..          ...          ...                ...         ...  ...     ...
345         346         Hari              UI/UX      Dharan   21  Female
346         347       Anisha  Digital Marketing  Biratnagar   31  Female
347         348         Sita            Flutter  Biratnagar   19    Male
348         349       Anisha              UI/UX     Itahari   27    Male
349         350         Hari  Python with AI/ML      Dharan   19  Female

    enrollment_date  course_fee  discount payment_status  attendance_percent  \
0        2026-02-24       10000        10        Pending                73.0
1        2026-06-29       10000        20        Pending                68.0
2        2026-02-20        5000        20           Paid                71.0
3        2026-05-23        7000         0        Pending                88.0
4        2026-05-28        5000         0        Pending               100.0
..              ...         ...       ...            ...                 ...
345      2026-06-17       10000        20           Paid                98.0
346      2026-03-21        5000        10           Paid                45.0
347      2026-02-05        5000        20           Paid                80.0
348      2026-05-05        5000        10           Paid                63.0
349      2026-04-04        5000        20        Pending                84.0

     assignment_score  final_score  rating     mentor       phone  \
0                  46           98       5  Samriddha  9839323411
1                  31           63       3     Manish  9874340113
2                  31           99       5  Samriddha  9874168652
3                  43           38       5     Manish  9864252889
4                  89           98       5      Ishan  9864166467
..                ...          ...     ...        ...         ...
345                87           56       5  Samriddha  9873827203
346                51           44       3  Samriddha  9864328504
347                89           39       5  Samriddha  9821459197
348                58           52       5      Ishan  9862269669
349                57           62       3     Manish  9803556080

                 email completion_status
0      user0@gmail.com           Ongoing
1      user1@gmail.com         Completed
2      user2@gmail.com         Completed
3      user3@gmail.com           Ongoing
4      user4@gmail.com           Ongoing
..                 ...               ...
345  user345@gmail.com           Ongoing
346  user346@gmail.com           Ongoing
347  user347@gmail.com         Completed
348  user348@gmail.com         Completed
349  user349@gmail.com           Ongoing

[349 rows x 18 columns]

In [47]:
#replace outliers with median
median = df[cols].median()
df[cols] = df[cols].where((df[cols] >= lower_bound) & (df[cols] <= upper_bound),median,axis=1)
print(df)

     student_id student_name             course        city  age  gender  \
0             1         Gita         MERN Stack   Kathmandu   17  Female
1             2        Nabin       Data Science     Itahari   29  Female
2             3         Gita         MERN Stack      Dharan   20  Female
3             4         Gita  Digital Marketing     Itahari   20  Female
4             5         Gita       Data Science     Itahari   19    Male
..          ...          ...                ...         ...  ...     ...
345         346         Hari              UI/UX      Dharan   21  Female
346         347       Anisha  Digital Marketing  Biratnagar   31  Female
347         348         Sita            Flutter  Biratnagar   19    Male
348         349       Anisha              UI/UX     Itahari   27    Male
349         350         Hari  Python with AI/ML      Dharan   19  Female

    enrollment_date  course_fee  discount payment_status  attendance_percent  \
0        2026-02-24       10000        10        Pending                73.0
1        2026-06-29       10000        20        Pending                68.0
2        2026-02-20        5000        20           Paid                71.0
3        2026-05-23        7000         0        Pending                88.0
4        2026-05-28        5000         0        Pending               100.0
..              ...         ...       ...            ...                 ...
345      2026-06-17       10000        20           Paid                98.0
346      2026-03-21        5000        10           Paid                45.0
347      2026-02-05        5000        20           Paid                80.0
348      2026-05-05        5000        10           Paid                63.0
349      2026-04-04        5000        20        Pending                84.0

     assignment_score  final_score  rating     mentor       phone  \
0                  46           98       5  Samriddha  9839323411
1                  31           63       3     Manish  9874340113
2                  31           99       5  Samriddha  9874168652
3                  43           38       5     Manish  9864252889
4                  89           98       5      Ishan  9864166467
..                ...          ...     ...        ...         ...
345                87           56       5  Samriddha  9873827203
346                51           44       3  Samriddha  9864328504
347                89           39       5  Samriddha  9821459197
348                58           52       5      Ishan  9862269669
349                57           62       3     Manish  9803556080

                 email completion_status
0      user0@gmail.com           Ongoing
1      user1@gmail.com         Completed
2      user2@gmail.com         Completed
3      user3@gmail.com           Ongoing
4      user4@gmail.com           Ongoing
..                 ...               ...
345  user345@gmail.com           Ongoing
346  user346@gmail.com           Ongoing
347  user347@gmail.com         Completed
348  user348@gmail.com         Completed
349  user349@gmail.com           Ongoing

[350 rows x 18 columns]

In [50]:
#windorization using clip()
df[cols] = df[cols].clip(lower=lower_bound, upper=upper_bound, axis=1)
print(df[cols].describe())

         course_fee  attendance_percent  assignment_score  final_score
count    350.000000          350.000000        350.000000   350.000000
mean    7277.142857           70.154286         67.040000    65.011429
std     2076.003671           16.673991         20.593726    20.556718
min     5000.000000           40.000000          5.000000    30.000000
25%     5000.000000           58.000000         51.000000    47.000000
50%     7000.000000           70.000000         69.000000    65.000000
75%    10000.000000           83.000000         85.750000    82.000000
max    10000.000000          100.000000        100.000000   100.000000

In [9]:
#z_score
z_scores = (df[cols] - df[cols].mean()) / df[cols].std()
z_outlier = (z_scores > 3) | (z_scores < -3)
outliers_df = df[z_outlier.any(axis=1)]
print(outliers_df)

    student_id student_name        course       city  age  gender  \
18          19         Sita       Flutter  Kathmandu   24    Male
38          39       Anisha  Data Science    Itahari   20  Female

   enrollment_date  course_fee  discount payment_status  attendance_percent  \
18      2026-05-09      999999        10        Pending                41.0
38      2026-01-14       10000        10        Pending                70.0

    assignment_score  final_score  rating  mentor       phone  \
18                75           51       4   Ishan  9803681891
38                -5           55       3  Manish  9856058698

               email completion_status
18  user18@gmail.com           Ongoing
38  user38@gmail.com           Ongoing